var usurName = prompt("Ismingizni kiriting: ");
console.log(usurName);
var usurSurname = prompt("Familiyangizni kiriting: ");
console.log(usurSurname);
var usurAge = prompt("Yoshingizni kiriting: ");
console.log(usurAge);
var usurEmail = prompt("Email kiriting: ");
console.log(usurEmail);
var usurParol = prompt("Parol kiriting(4ta sondan iborat bo'lsin): ");
console.log(usurParol);